### ISSUE TITLE
Not able to update chromium driven

### ISSUE THREAD

**Issue by aFluxx** [staudenmeir/dusk-updater#11]
Hello there,

I seem to have a problem when updating the driver. I run `php artisan:dusk update` and it tells me that it's updated, but when I run `--detect` the old version still persists`.

![](https://i.gyazo.com/c5e719a91ac592e285ab0ddaa8316ccc.png)

And the version I'm running:
```json
"name": "staudenmeir/dusk-updater",
            "version": "v1.1.3",
            "source": {
                "type": "git",
                "url": "https://github.com/staudenmeir/dusk-updater.git",
                "reference": "f3450cb8dbb9fdbc1a1aee144c666a44983394c2"
            },
```

**Comment by staudenmeir** [comment]
That's expected behavior:
- `php artisan:dusk update` downloads the latest stable ChromeDriver release (78.0.3904.70).
- `php artisan:dusk update --detect` downloads the ChromeDriver that matches the installed Chrome/Chromium version (in your case: 77).

**Comment by aFluxx** [comment]
Ooooh I'm sorry, I tought that was to see which version I was running! My bad.

Well the problem is that if I just run update, I get this flickering when I run dusk. A browser would open and immedetially close, normally if I just ran update this problem would be gone, but now I can't seem to update.

**Comment by staudenmeir** [comment]
Can you update the browser to the latest version?

**Comment by aFluxx** [comment]
Sorry I haven't come back to this, but updating the browser itself fixed the issue!
