### ISSUE TITLE
Add To Dusk Core

### ISSUE THREAD

**Issue by browner12** [staudenmeir/dusk-updater#12]
It's been 9 months since someone tried to PR this into Dusk core, and I think Taylor may have been originally spooked a bit by the concerns you rose.

Would you be willing to try again to add the to the core Dusk repo, as I think it would be of considerable use to **all** Dusk users?

**Comment by staudenmeir** [comment]
The package's main functionality is actually already available in Dusk:
https://laravel.com/docs/6.x/dusk#managing-chromedriver-installations

The [PR](https://github.com/laravel/dusk/pull/645) you have in mind was only about the Chrome version detection ;-)

**Comment by browner12** [comment]
Sorry, yes. I was just referring to the Chrome version detection. I think that would be very beneficial to add to core.

**Comment by staudenmeir** [comment]
I'll think about it.
