### ISSUE TITLE
php artisan dusk:update --detect not working, Error: Chrome version could not be detected

### ISSUE THREAD

**Issue by sagautam5** [staudenmeir/dusk-updater#14]
In my local environment, php artisan dusk fails because of chrome driver.

I have installed google chrome and it's driver recently. I have run dusk update with following command,

`php artisan dusk:update`

It's updating the driver and this is console output:

`ChromeDriver binaries successfully updated to version 88.0.4324.96.`

Now, when I run the detect command, it shows following error:

Chrome version could not be detected. Please submit an issue: https://github.com/staudenmeir/dusk-updater

`php artisan dusk` is failing even after `php artisan dusk:update` 

I am using v1.1.3.

**Comment by staudenmeir** [comment]
What OS are you using? Is the local environment inside a virtual machine (e.g. Homestead)?

**Comment by sagautam5** [comment]
> What OS are you using? Is the local environment inside a virtual machine (e.g. Homestead)?

Hello sir, I am using ubantu 16.04 and docker for development environment

**Comment by staudenmeir** [comment]
What version of Dusk are you using?
