### ISSUE TITLE
Larapack.io seems to be abandoned

### ISSUE THREAD

**Issue by Fijvect** [staudenmeir/dusk-updater#15]
Hello! When trying to install this package via composer, I get the error "curl error 60 while downloading https://larapack.io/packages.json: SSL certificate problem: certificate has expired"

After looking into it, it's definitely a larapack.io issue. And after going through the history of the github for larapack.io, it definitely seems like the project has been abandoned. 
Would you consider switching away from larapack?

Thanks!

**Comment by staudenmeir** [comment]
I've never heard of Larapack. How is it connected to the package? What's the whole error message?

**Comment by Fijvect** [comment]
You're right, sorry! I thought this had to do with your package, but after looking through the stacktrace, it seems it's failing on composer's booting sequence...so probably something on my end. 
I'll close this.
