### ISSUE TITLE
Curl Error

### ISSUE THREAD

**Issue by ghost** [staudenmeir/dusk-updater#3]
I don't believe this is an issue with your package but maybe you can help. 

I am using your package to get the latest chrome drivers but every-time I run `php artisan dusk` I get this ```Facebook\WebDriver\Exception\WebDriverCurlException: Curl error thrown for http POST to /session with params: {"desiredCapabilities":{"browserName":"chrome","platform":"ANY","chromeOptions":{"binary":"","args":["--disable-gpu","--headless"]}}}```

If I manually download and run the chrome exe then it works. Any thoughts on how to fix this?

**Comment by staudenmeir** [comment]
By "chrome exe" you mean the `chromedriver.exe`?
