### ISSUE TITLE
session not created: Chrome version must be between 71 and 75

### ISSUE THREAD

**Issue by ryancwalsh** [staudenmeir/dusk-updater#6]
This tool is a great idea; thank you for writing it.

Even after running your command, I'm getting:

```
Facebook\WebDriver\Exception\SessionNotCreatedException: session not created: Chrome version must be between 71 and 75
  (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-116-generic x86_64)
```

So I searched through this repo's issues and found https://github.com/staudenmeir/dusk-updater/issues/5, which led me to see at https://github.com/staudenmeir/dusk-updater that you'd said "If Dusk is still using the previous version after the update, there is probably an old ChromeDriver process running."

I suggest moving that to an earlier and more prominent step (and clarify what you're saying to do) since almost always people will need to consider that.

I tried `pkill chrome` and `pkill Xvfb`, but neither helped. 

I also tried exiting out of the Vagrant SSH and then running `homestead.bat reload --provision` before SSHing back in, but I still get the same error.

Any ideas?

Thanks so much!

**Comment by staudenmeir** [comment]
This looks like a different issue. Dusk is using the latest Chrome*Driver* (2.46), but Chrome/Chromium itself is not up-to-date.

Try updating it: `sudo apt-get install --only-upgrade chromium-browser`

**Comment by ryancwalsh** [comment]
Yeah you were right; I just figured that out, too. Thanks so much, Jonas!
