### ISSUE TITLE
Not update to specific version (or latest)

### ISSUE THREAD

**Issue by edbizarro** [staudenmeir/dusk-updater#7]
The latest version of ChromeDriver supports Chrome 74 but when I run the command `php artisan dusk:update 74` (or without the version) it informs that the installed version is v71-73 compatible.

`ChromeDriver binaries successfully updated to version 2.46 (Chrome v71-73)`

[Ref ](http://chromedriver.chromium.org/downloads)

**Comment by staudenmeir** [comment]
I'm working on a solution.

**Comment by edbizarro** [comment]
Thanks!

**Comment by staudenmeir** [comment]
The latest release `v1.0.3` supports the new ChromeDriver release strategy.

**Comment by edbizarro** [comment]
Confirm that `v1.0.3` fix the issue
