### ISSUE TITLE
It cannot update to specific version for 76

### ISSUE THREAD

**Issue by ramseyjiang** [staudenmeir/dusk-updater#8]
php artisan dusk:update --detect
Chrome version 76.0.3809.87 detected.

When I try to "php artisan dusk:update 76.0.3809.87", it has errors as following:

   ErrorException  : fopen(https://chromedriver.storage.googleapis.com/76.0.3809.87/chromedriver_linux64.zip): failed to open stream: HTTP request failed! HTTP/1.0 404 Not Found

  at /vendor/staudenmeir/dusk-updater/src/UpdateCommand.php:248
    244|         $archive = $this->directory.'chromedriver.zip';
    245| 
    246|         $url = sprintf(static::$downloadUrl, $version, $slug);
    247| 
  > 248|         file_put_contents($archive, fopen($url, 'r'));
    249| 
    250|         return $archive;
    251|     }
    252| 

  Exception trace:

  1   fopen("https://chromedriver.storage.googleapis.com/76.0.3809.87/chromedriver_linux64.zip", "r")
      /vendor/staudenmeir/dusk-updater/src/UpdateCommand.php:248

  2   Staudenmeir\DuskUpdater\UpdateCommand::download("76.0.3809.87", "linux64")
      /vendor/staudenmeir/dusk-updater/src/UpdateCommand.php:227

  Please use the argument -v to see more details.

**Comment by staudenmeir** [comment]
`76.0.3809.87` is the Chrome browser version,t he matching Chrome*Driver* version is `76.0.3809.68`:

```console
php artisan dusk:update 76.0.3809.68
```

You can also just use `php artisan dusk:update --detect` or `php artisan dusk:update 76`.

**Comment by staudenmeir** [comment]
I just saw your comment in https://github.com/laravel/dusk/issues/641.

When the output says "No update necessary", you are already using the correct ChromeDriver version.

**Comment by ramseyjiang** [comment]
> I just saw your comment in [laravel/dusk#641](https://github.com/laravel/dusk/issues/641).
> 
> When the output says "No update necessary", you are already using the correct ChromeDriver version.

But when I used 68 to run php artisan dusk, it will show me errors.

Facebook\WebDriver\Exception\SessionNotCreatedException: session not created
from disconnected: unable to connect to renderer
  (Session info: headless chrome=76.0.3809.87)
  (Driver info: chromedriver=76.0.3809.68 (420c9498db8ce8fcd190a954d51297672c1515d5-refs/branch-heads/3809@{#864}),platform=Mac OS X 10.14.5 x86_64)
